account/urls.py
from django.contrib import admin
from django.urls import path,include
from signup.views import main
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main, name='main'),
    path('signup/', include('signup.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

signup/urls.py
from django.urls import path
from .views import signup,login,logout,mypage,home,edit_profile,delete_Guestbook,todolist,delete_Todolist, toggle_todo,post_write,post_list,post, post_edit, delete_post


app_name='signup'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('mypage/', mypage, name='mypage'),
    path('home/', home, name='home'),
    path('mypage/edit/', edit_profile, name='edit'),
    path('delete_Guestbook/<int:entry_id>/', delete_Guestbook, name='delete_Guestbook'),
    path('todolist/',todolist, name='todolist'),
    path('delete_Todolist/<int:todo_id>/',delete_Todolist,name='delete_Todolist'),
    path('toggle_todo/<int:todo_id>/', toggle_todo, name='toggle_todo'),
    path('post_write/', post_write, name='post_write'),
    path('post_list/',post_list,name='post_list'),
    path('post/<int:post_id>/', post, name = 'post'),
    path('post/<int:post_id>/edit/', post_edit, name='post_edit'),
    path('delete_post/<int:post_id>/', delete_post,name='delete_post'),
]

signup/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.contrib.auth.hashers import make_password
#장고에서 기본적으로 제공해주는 유저 커스텀해서 만드는거

class UserManager(BaseUserManager):

    def create_user(self, id, name, email, major, nickname, phone_number ,password=None):

        if not id:
            raise ValueError('아이디좀 입력해주세요')
        user = self.model(
            id=id,
            name=name,
            email=self.normalize_email(email),
            major=major,
            nickname=nickname,
            phone_number = phone_number,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

#슈퍼유저 만드는거
    def create_superuser(self, id, name, email, major, nickname, phone_number, password):
        user = self.create_user(
            id=id,
            name=name,
            email=self.normalize_email(email),
            major=major,
            nickname=nickname,
            password=password,
            phone_number = phone_number,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

class CustomUser(AbstractBaseUser):
    user_number = models.AutoField(primary_key=True)
    id = models.CharField(max_length=15, unique=True, null=False, blank=False)
    #중복방지 primary_key=True
    name = models.CharField(max_length=30)
    email = models.EmailField(default='', max_length=100, null=False, blank=False, unique=True)
    major = models.CharField(max_length=30)
    nickname = models.CharField(max_length=10, unique=True)
    phone_number = models.CharField(max_length=13)
    #아래 두개는 필수 필드라고 합니다!
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    profile_pic = models.ImageField(upload_to='profile_pics/', blank=True)
    hobby = models.CharField(max_length=100, blank=True)
    address = models.CharField(max_length=200, blank=True)
    objects = UserManager() #위에서 정의한 헬퍼 클래스 불러와서 

    USERNAME_FIELD = 'id'
    #필수로 작성해야하는 필드 명시
    REQUIRED_FIELDS = ['email','nickname','name','phone_number']

    def __str__(self):
        return self.id

#admin페이지에서 오류 잡는 용도입니다
    @property
    def is_staff(self):
        return self.is_admin
    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True
    
class GuestbookEntry(models.Model):
    name= models.CharField(max_length=100)
    message= models.TextField()
    guest_password= models.CharField(max_length=15,default='admin')
    created_at= models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name}-{self.created_at}'
    
class Todo(models.Model):
    # date=models.DateTimeField(auto_now=False, auto_now_add=False)
    text=models.TextField()
    completed = models.BooleanField(default=False)

class Post(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='posts')
    content= models.TextField()
    secret = models.BooleanField(default= False)
    created_at = models.DateTimeField(auto_now_add=True)
    password = models.CharField(max_length=128, blank=True)

    def save(self, *args, **kwargs):
        # 비밀번호가 입력된 경우에만 해싱하여 저장
        if self.password:
            self.password = make_password(self.password)
        super().save(*args, **kwargs)

signup/forms.py
from django import forms
from .models import CustomUser,Todo,GuestbookEntry, Post


class SignUpForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password check', widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('id','name','email','major','nickname','phone_number')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class UserProfileUpdateForm(forms.ModelForm):
   class Meta:
        model = CustomUser
        fields = [ 'nickname','major', 'profile_pic','hobby', 'address']
        widgets = {
            'profile_pic': forms.FileInput(attrs={'class': 'form-control-file'}),
        }

class GuestbookForm(forms.ModelForm):
    class Meta:
        model= GuestbookEntry
        fields=['name','message','guest_password']

class TodoForm(forms.ModelForm):
    class Meta:
        model= Todo
        fields=['text']
        widgets={
            'completed':forms.CheckboxInput()
        }

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields=['title', 'content'] 
        widgets={
            'secret': forms.CheckboxInput(),
            # 'secret': forms.CheckboxInput(attrs={'id': 'secret_checkbox'}),
            # 'password': forms.PasswordInput(attrs={'style': 'display:none;', 'id': 'password_input'})
        }
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(PostForm, self).__init__(*args, **kwargs)
        if user and user.is_authenticated:
            self.fields['nickname'] = forms.CharField(max_length=10, widget=forms.HiddenInput, initial=user.nickname)
        # self.fields['password'].label = '비밀번호'
        

signup/views.py
from django.shortcuts import render, redirect
from .forms import SignUpForm,UserProfileUpdateForm,GuestbookForm,TodoForm,PostForm,Post
from django.contrib import auth, messages
from .models import CustomUser,GuestbookEntry,Todo
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import get_object_or_404
from django.http import HttpResponse, JsonResponse,HttpResponseForbidden
from django.contrib.auth.hashers import check_password



# Create your views here.
def signup(request):
    if request.method=='POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'main.html')
        return render(request, 'signup.html', {'form': form })
    else:
        form = SignUpForm()
        return render(request, 'signup.html', {'form': form } )

def login(request):
    if request.method=='POST':
        id=request.POST.get('id')
        password=request.POST.get('password')
        user=auth.authenticate(request, id = id, password = password)
        #print(user)
        if user is not None:
            auth.login(request, user)
            return redirect('signup:home')
        else:
            return render(request, 'login.html')
    else:
        return render(request, 'login.html')
    
def logout(request):
    auth.logout(request)
    return redirect('main')

# def main(request):
#     return render(request,'main.html')

def mypage(request):
    return render(request, 'mypage.html')

@login_required
def home(request):
    return render(request,'home.html')

def edit(request):
    return render(request,'mypage_edit.html')

def edit_profile(request):
    if request.method == 'POST':
        form = UserProfileUpdateForm(request.POST, request.FILES, instance=request.user)
        try:
            form.image=request.FILES['image']
        except: #이미지가 없어도 그냥 지나가도록-!
            pass
        if form.is_valid():
            form.save()
            messages.success(request, '프로필이 성공적으로 업데이트되었습니다.')
            return redirect('/signup/mypage')
    else:
        form = UserProfileUpdateForm(instance=request.user)
    
    return render(request, 'mypage_edit.html', {'form': form})

def main(request):
    if request.method=='POST':
        form=GuestbookForm(request.POST)
        if form.is_valid():
            name = request.POST['name']
            message= request.POST['message']
            password= form.cleaned_data['password']
            entry= GuestbookEntry(name= name,message=message,guest_password= password)
            entry.save()
            return redirect('main')
    else:
        form =GuestbookForm()

    entries= GuestbookEntry.objects.all()
    return render(request,'main.html', {'form':form,'entries':entries})

@csrf_exempt
def delete_Guestbook(request, entry_id):
    if request.method=='POST':
        entry = GuestbookEntry.objects.get(pk=entry_id)
        password= request.POST.get('password', '')
        if password == entry.guest_password:
            entry.delete()
            messages.success(request,'방명록이 삭제되었습니다.')
        else:
            messages.error(request,'비밀번호가 올바르지 않습니다.')
    return redirect('main')

@login_required
def todolist(request):
    if request.method=='POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            # text= request.POST['text']
            # completed = request.POST['completed']
            # entry= Todo(text='text', completed='completed')
            # entry.save()
            form.save()
            return redirect('signup:todolist')
    else:
        form= TodoForm()
    todo_list = Todo.objects.all()
    return render(request,'todolist.html', {'form':form, 'todo_list':todo_list})

def delete_Todolist(request,todo_id):
    todo = get_object_or_404(Todo, id=todo_id)
    if request.method=='POST':
        todo.delete()
        return redirect('signup:todolist')
    return render(request, 'todolist.html',{'todolist':todolist})

@login_required
def toggle_todo(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    todo.completed = not todo.completed  # Toggle the completed status
    todo.save()
    return redirect('signup:todolist')

@login_required
def post_write(request):
    if request.method=='POST':
        form = PostForm(request.POST,user=request.user)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            form.save()
            return redirect('signup:post', post_id=post.id)
    else:
        form = PostForm(user=request.user)
    posts=Post.objects.all()
    return render(request,'post_write.html', {'form':form,'posts':posts})

@login_required
def post_list(request):
    posts = Post.objects.all()
    return render(request, 'post_list.html', {'posts': posts})

@login_required
def post(request,post_id):
    post = get_object_or_404(Post, pk=post_id)  # 해당 post_id에 해당하는 Post 객체를 가져옴
    # if post.secret:
    #     if request.method == 'POST':
    #         password = request.POST.get('password')
    #         if password == post.password:
    #             return render(request, 'post.html', {'post': post})       
    # else:
    return render(request, 'post.html', {'post': post})

@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post, user=request.user)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            form.save()
            return redirect('signup:post', post_id=post_id)
    else:
        form = PostForm(instance=post, user=request.user)
    return render(request, 'post_edit.html', {'form': form, 'post':post})

def delete_post(request,post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method=='POST':
        post.delete()
        return redirect('signup:post_list')
    return render(request, 'post_list.html',{'post_list':post_list})

signup/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main Page</title>
</head>
<body>
    {% if user.is_authenticated %}
    <h1>Welcome to the Main Page!</h1>
    
    
    <button><a href="{% url 'signup:mypage' %}">mypage</a></button>

    <!-- 로그아웃 링크 -->
    <button><a href="{% url 'signup:logout' %}">logout</a></button>
    
    <button><a href="{% url 'signup:todolist' %}">to-do list</a></button>
    <button><a href="{% url 'signup:post_list' %}">게시판</a></button>


    {% endif %}

</body>
</html>

signup/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'signup:login' %}" method="POST">
        {% csrf_token %}
        id: <input type="id" name="id"><br>
        password: <input type="password" name="password"><br>
        <input type="submit" value="로그인">
    </form>
    
</body>
</html>

signup/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>메인 페이지</title>
</head>
<body>

<h2>환영합니다!</h2>

<a href="{% url 'signup:signup' %}">회원가입</a>
<a href="{% url 'signup:login' %}">로그인</a>

<h2>방명록 작성하기</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">방명록 작성</button>
    </form>
    
    <h2>방명록</h2>
    <ul>
        {% for entry in entries %}
            <li><strong>{{ entry.name }}</strong>: {{ entry.message }}
                <form method = "post" action = "{%url 'signup:delete_Guestbook' entry.id %}">
                    {% csrf_token %}
                    <input type ="password" name = "password" placeholder="비밀번호">
                    <button type = "submit"> 삭제</button>
                </form>
            </li>
        {% endfor %}
    </ul>
    
</body>
</html>

signup/templates/mypage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% csrf_token %}
    <p>username: {{ user.name }}</p>
    <p>nickname: {{ user.nickname }}</p>
    <p>major: {{ user.major }}</p>
    <p>ID: {{ user.id }}</p>
    <p>e-mail: {{ user.email }}</p>
    
    {% if user.profile_pic %}
        <p>프로필 사진:</p>
        <img src="{{ user.profile_pic.url }}" alt="프로필 사진"><br><br>
    {% endif %}

    {% if user.hobby %}
        <p>취미: {{ user.hobby }}</p>
    {% endif %}

    {% if user.address %}
        <p>주소: {{ user.address }}</p>
    {% endif %}
    <button><a href="{% url 'signup:edit' %}">정보 수정</a></button>
    <button><a href="{% url 'signup:home' %}">메인 페이지</a></button>

</body>
</html>

signup/templates/mypage_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>마이페이지 수정</title>
</head>
<body>
    <h1>마이페이지 수정</h1>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% comment %} <label for="nickname">닉네임:</label>
        <input type="text" id="nickname" name="nickname" value="{{ user.nickname }}"><br><br>

        <label for="major">전공:</label>
        <input type="text" id="major" name="major" value="{{ user.major }}"><br><br>

        <label for="profile_pic">프로필 사진:</label>
        <input type="file" id="profile_pic" name="profile_pic"><br><br>

        <label for="hobby">취미:</label>
        <input type="text" id="hobby" name="hobby"><br><br>

        <label for="address">주소:</label>
        <input type="text" id="address" name="address"><br><br> {% endcomment %}

        <form action="{%url 'signup:edit' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">저장</button>
          </form>
        <button><a href="{% url 'signup:mypage' %}">mypage</a></button>

    </form>
</body>
</html>

signup/templates/post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>게시글 상세 정보</title>
</head>
<body>
    <h1>{{ post.title }}</h1>
    <p>작성자: {{ post.author.nickname }}</p>
    <p>{{ post.content }}</p>
    <small>작성 시간: {{ post.created_at }}</small>
    <br>
    <button><a href="{% url 'signup:post_edit' post_id=post.id %}">수정</a></button>
    <form method="post" action="{% url 'signup:delete_post' post.id %}">
        {% csrf_token %}
        <button type="submit">삭제</button>
    </form>
    <button><a href="{% url 'signup:post_list' %}">목록으로 돌아가기</a></button>
</body>
</html>

signup/templates/post_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Post</title>
</head>
<body>
    <h1>게시글</h1>

    <form action="{% url 'signup:post_edit' post_id=post.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">작성</button>
    </form>

    <button><a href="{% url 'signup:post_list' %}">목록으로 돌아가기</a></button>
</body>

signup/templates/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>게시글</title>
</head>
<body>

<button><a href="{% url 'signup:post_write' %}">게시글 작성하기</a></button>

    <h2>게시글 목록</h2>
    <ul>
        {% for post in posts %}
            <li>
                <h2><a href="{% url 'signup:post' post_id=post.pk %}"></h2>
                <p>{{ post.title }}</a> 작성자: {{ post.author.nickname }} <small>{{ post.created_at }}</small></p>
            </li>
        {% endfor %}
    </ul>
        
</body>
</html>

signup/templates/post_write.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Post</title>
</head>
<body>
    <h1>게시글</h1>

    <form action="{% url 'signup:post_write' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {% comment %} <div id="password_field">
            <label for="password_input" id="password_label" style="display:none;">
            {{ form.password }}
        </div> {% endcomment %}
        <button type="submit">작성</button>
    </form>

    <button><a href="{% url 'signup:post_list' %}">목록으로 돌아가기</a></button>
    {% comment %} <script>
        var checkbox = document.getElementById('secret_checkbox');
        var passwordLabel = document.getElementById('password_label');
        var passwordInput = document.getElementById('password_input');

        checkbox.addEventListener('change', function() {
            if (this.checked) {
                passwordLabel.style.display = 'block';
                passwordInput.style.display = 'block';
            } else {
                passwordLabel.style.display = 'none';
                passwordInput.style.display = 'none';
            }
        });
    </script> {% endcomment %}
</body>

signup/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
  <ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|safe }}</li>
    {% endfor %}
  </ul>
    <form action="{%url 'signup:signup' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
      </form>
</body>
</html>

signup/templates/todolist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>To-Do List</title>
      
</head>
<body>

<button><a href="{% url 'signup:home' %}">돌아가기</a></button>

<h2>To-Do List</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add</button>
</form>

<ul>
    {% for todo in todo_list %}
    <li style="display: flex;">
        <form method="post" action="{% url 'signup:toggle_todo' todo.id %}">
            {% csrf_token %}
            <input type="checkbox" {% if todo.completed %}checked{% endif %} onchange="this.form.submit()">
        </form>
        <textarea readonly style="width: 500px; height: 50px; margin-right: 10px; border: none; background-color: transparent;">{{ todo.text }}</textarea>
        <form method="post" action="{% url 'signup:delete_Todolist' todo.id %}">
            {% csrf_token %}
            <button type="submit">삭제</button>
        </form>
    </li>
    {% endfor %}
</ul>

</body>
</html>